server:
  port: 8280

spring:
  application:
    name: rule-engine
  datasource:
    url: jdbc:mysql://10.23.103.132:3306/rule-engine
    username: root
    password: Bb123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: 10.23.103.132
    port: 5672
    username: rabbit
    password: 12345678
    virtual-host: iot
#    listener:
#      simple:
#        acknowledge-mode: auto
#        retry:
#          enabled: true
#          max-attempts: 5
#          initial-interval: 2s
  redis:
    host: 10.23.103.132
    port: 6379
    client-type: LETTUCE
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        max-wait: 300ms
  cloud:
    nacos:
      discovery:
        server-addr: 10.23.103.132:8848

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml

biot:
  tsdb:
    influx:
      host: http://10.23.103.132:8086
      token: TNPoc-yJwKzeTrL1yIWsQZQGKcH-g6ytu09nLVZezudfFnpI4PVW2IIqDlXp6Kjn0MPzaEgWHSbBUTRYe6546g==
      org: abama
      trigger_bucket: rule_trigger_trace