spring:
  application:
    name: rule-engine
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
  config:
    import:
      #- optional:nacos:rule-engine.yaml
      - optional:local.yml # 本地配置

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml